language: node_js
node_js:
  - 'node'
  - '6'
  - '4'
addons:
  code_climate:
    repo_token: 'your repo token'
notifications:
  email: false
services:
  - elasticsearch
before_script:
  - sleep 10
  - npm install -g codeclimate-test-reporter
  - npm install -g --only=dev
after_script:
  - codeclimate-test-reporter < coverage/lcov.info